# Generated by Django 2.0.4 on 2018-05-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_auto_20180501_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='published_date',
        ),
    ]
