# Generated by Django 2.0.4 on 2018-05-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_remove_usuario_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Nombre1',
            new_name='Identificacion',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Nombre2',
            new_name='Nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Cedula',
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
