# Generated by Django 2.0.4 on 2018-05-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_auto_20180519_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
