# Generated by Django 2.0.4 on 2018-05-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0005_auto_20180519_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default=11, max_length=40),
            preserve_default=False,
        ),
    ]
