# Generated by Django 2.0.4 on 2018-05-01 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0002_auto_20180410_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='tipo_solicitud',
        ),
    ]
