# Generated by Django 2.0.4 on 2018-05-01 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0003_auto_20180501_0025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administrador',
            new_name='Funcionario',
        ),
    ]
