# Generated by Django 2.0.4 on 2018-05-21 20:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0007_auto_20180520_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad_emisora',
            fields=[
                ('id_lugar', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad_receptora',
            fields=[
                ('id_lugar', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id_lugar', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('Numero_solicitud', models.IntegerField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_solicitud',
            fields=[
                ('id_solicitud', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Lugar_de_trabajo',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='Cargo',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, to='Administrador.Cargos'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='Cedula',
            field=models.IntegerField(default=0, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='Asunto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Tipo_solicitud'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='entidad_emisora',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Entidad_emisora'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='entidad_receptora',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Entidad_receptora'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Funcionario'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='lugar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Lugar'),
        ),
        migrations.AddField(
            model_name='entidad_receptora',
            name='lugar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Lugar'),
        ),
        migrations.AddField(
            model_name='entidad_emisora',
            name='lugar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Lugar'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='Cede',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, to='Administrador.Entidad_emisora'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='lugar',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, to='Administrador.Lugar'),
        ),
    ]
