# Generated by Django 2.0.4 on 2018-05-23 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0008_auto_20180521_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='Cedula',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Administrador.Funcionario'),
        ),
    ]
