# Generated by Django 2.0.4 on 2018-05-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0009_auto_20180523_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='Cedula',
            field=models.CharField(default='NONE', max_length=10, primary_key=True, serialize=False),
        ),
    ]
