# Generated by Django 2.0.4 on 2018-05-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0014_auto_20180523_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='Cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
