# Generated by Django 2.0.4 on 2018-05-24 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0015_auto_20180523_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cede',
            fields=[
                ('id_Cede', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=40)),
                ('lugar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Lugar')),
            ],
        ),
        migrations.RemoveField(
            model_name='cargos',
            name='id',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='lugar',
        ),
        migrations.AddField(
            model_name='cargos',
            name='id_Cargo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='Cede',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Cede'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='Numero_solicitud',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
