# Generated by Django 2.0.4 on 2018-05-24 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0016_auto_20180524_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='Cargo',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='Cede',
            new_name='cede',
        ),
    ]
