# Generated by Django 2.0.4 on 2018-05-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0018_auto_20180525_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_solicitud',
            name='id_solicitud',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
