# Generated by Django 2.0.4 on 2018-05-28 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0020_auto_20180527_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='revisado',
        ),
    ]
