# Generated by Django 2.0.4 on 2018-05-28 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0021_remove_solicitud_revisado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='Asunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Tipo_solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='entidad_emisora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Entidad_emisora'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='entidad_receptora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Entidad_receptora'),
        ),
    ]
